name: gest_ultrassom
description: Gest Ultrassom - Agendamento inteligente de exames prÃ©-natais
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  # firebase_core: ^2.24.2  # Temporariamente desabilitado para build web
  # firebase_messaging: ^14.7.10  # Temporariamente desabilitado para build web
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  http: ^1.2.0
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
